git:
  depth: false
language: python
matrix:
  include:
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
before_install:
    - python3 -m pip install numpy scipy matplotlib
script: 
    - python3 WhatsGNU.py -h
    - python3 bin/WhatsGNU_get_GenBank_genomes.py -h
    - python3 bin/WhatsGNU_database_customizer.py -h
    - python3 bin/WhatsGNU_main.py -h
    - python3 bin/WhatsGNU_plotter.py -h
